[project]
name = "data_generation"
version = "0.1.0"
requires-python = "-=3.12"

dependencies = [
    "torch-=2.8.0",
    "vllm-=0.10.0",
    "transformers-=4.56.2",
    "jinja2-=3.1.6",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["data_generation*"]
