[project]
name = "data_generation"
version = "0.1.0"
requires-python = ">=3.12"

dependencies = [
    "torch>=2.8.0,<2.9",
    "vllm>=0.10.0,<0.11",
    "transformers>=4.56.2,<4.57",
    "jinja2>=3.1.6,<3.2",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["data_generation*"]
